/*
 * [389] Find the Difference
 *
 * https://leetcode.com/problems/find-the-difference
 *
 * Easy (51.17%)
 * Total Accepted:
 * Total Submissions:
 * Testcase Example:  '"abcd"\n"abcde"'
 *
 *
 * Given two strings s and t which consist of only lowercase letters.
 *
 * String t is generated by random shuffling string s and then add one more
 * letter at a random position.
 *
 * Find the letter that was added in t.
 *
 * Example:
 *
 * Input:
 * s = "abcd"
 * t = "abcde"
 *
 * Output:
 * e
 *
 * Explanation:
 * 'e' is the letter that was added.
 *
 */
class Solution {
public:
    char findTheDifference(string s, string t) {
        char c = t[0];
        for(int i = 0; i < s.size(); i++){
            c ^= s[i];
            c ^= t[i+1];
        }
        return (char)c;
    }
};
